apiVersion: v1
kind: Secret
metadata:
  name: worldmonitor-secrets
  labels:
    app.kubernetes.io/part-of: worldmonitor
type: Opaque
stringData:
  REDIS_PASSWORD: "change-me-redis-password"
  REDIS_TOKEN: "change-me-redis-rest-token"
  SRH_TOKEN: "change-me-redis-rest-token"
  SRH_CONNECTION_STRING: "redis://:change-me-redis-password@redis:6379"
  RELAY_SHARED_SECRET: "change-me-relay-shared-secret"
  LLM_API_URL: ""
  LLM_API_KEY: ""
  LLM_MODEL: ""
  GROQ_API_KEY: ""
  AISSTREAM_API_KEY: "demo-aisstream-key"
  FINNHUB_API_KEY: ""
  EIA_API_KEY: ""
  FRED_API_KEY: ""
  ACLED_ACCESS_TOKEN: ""
  NASA_FIRMS_API_KEY: ""
  CLOUDFLARE_API_TOKEN: ""
  AVIATIONSTACK_API: ""
